for name in ABP ALT AMS AMY ASC ASK AVI AZR BAL BHD BKT BME BMW BRW BSC CBA CGO CHR CIB CMO CPT CRZ DRP DSI EIC GMI GOZ HBA HPB HUN ICE IZO KEY KUM KZD KZM LEF LLB LLN LMP MBC MEX MHD MID MKN MLO NAT NMB NWR OPW OXK PAL POC000 POCN05 POCN10 POCN15 POCN20 POCN25 POCN30 POCS05 POCS10 POCS15 POCS20 POCS25 POCS30 POCS35 PSA PTA RPB SCSN03 SCSN06 SCSN09 SCSN12 SCSN15 SCSN18 SCSN21 SDZ SEY SGP SHM SMO SPO STC STM SUM SYO TAP THD TIK USH UTA UUM WIS WLG ZEP 
do
wget ftp://aftp.cmdl.noaa.gov/data/trace_gases/co2/flask/surface/co2_${name,,}_surface-flask_1_ccgg_month.txt
done
