for name in ABP ALT AMY ASC ASK AZR BAL BHD BKT BME BMW BRW BSC CBA CGO CHR CIB CPT CRZ DRP DSI EIC GMI HBA HPB HUN ICE ITN IZO KEY KUM KZD KZM LEF LLB LLN LMP MEX MHD MID MKN MLO NAT NMB NWR OXK PAL POC000 POCN05 POCN10 POCN15 POCN20 POCN25 POCN30 POCS05 POCS10 POCS15 POCS20 POCS25 POCS30 PSA PTA RPB SDZ SEY SGP SHM SMO SPO STM SUM SYO TAP THD TIK USH UTA UUM WIS WKT WLG ZEP
do
wget ftp://aftp.cmdl.noaa.gov/data/trace_gases/n2o/flask/surface/n2o_${name,,}_surface-flask_1_ccgg_month.txt
done
